import React, { useEffect, useState, Fragment, useCallback } from "react";
import "./App.css";
import { HostSession } from "./components/session/hostSession/HostSession";
import { Menu } from "./components/menu/Menu";
import { ParticipantSession } from "./components/session/userSession/ParticipantSession";
import { PostSession } from "./components/postSession/PostSession";
import { SessionState } from "./contexts/SessionState";
import { socket } from "./components/service/socket";

function App() {
  /**
   * Returns a component based on the users context within the app.
   * @summary Default context is 0 and returns a menu. The state object also includes a room pin which
   * is generated by the server, as well as a socket that is imported from file.
   * @return {JSX} A main component within the app.
   */

  const [userContext, setUserContext] = useState({
    appContext: 0,
    roomPin: null,
    activeSocket: socket,
  });

  useEffect(() => {
    console.log("user context from reload app: ", userContext);
  }, [userContext["appContext"]]);

  return (
    <SessionState.Provider value={{ userContext, setUserContext }}>
      {userContext["appContext"] === 0 && <Menu />}
      {userContext["appContext"] === 1 && <HostSession />}
      {userContext["appContext"] === 2 && <ParticipantSession />}
      {userContext["appContext"] === 3 && <PostSession />}
    </SessionState.Provider>
  );
}

export default App;
